### PR TITLE
establishing connection to mongodb database

### PR DESCRIPTION
**Pull request by timkoukarine**

### CODE REVIEW

**Comment by timkoukarine** [comment]
guys please help me merge this before its too far gone

**Comment by tasnimreza** [comment]
uhoh

**Comment by tasnimreza** [comment]
Screen Shot 2024-07-18 at 9 50 55 AM
HAHA goodluck to us fr. lets try and solve it in lab tday

**Comment by timkoukarine** [comment]
Agreed 🤝

**Pull request closed without merging**
